# This deployment is separate in this directory as it will be used to test kafka consumer

apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafkatest
  name: kafkatest
spec:
  type: NodePort
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    service: kafkatest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: kafkatest
  name: kafkatest
spec:
  replicas: 1
  selector:
    matchLabels:
      service: kafkatest
  template:
    metadata:
      labels:
        service: kafkatest
    spec:
      containers:
      - image: sitgesfer/kafkatest
        name: kafkatest
        imagePullPolicy: Always
      restartPolicy: Always
